services:

  postgres:
    image: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: ${SPRING_DATASOURCE_DB}

    ports:
      - "5432:5432"
    volumes:
      - ./postges:/var/lib/postgesql/data

  # adminer:
  #   image: adminer
  #   restart: always
  #   ports:
  #   volumes:
  #     - ./postges:/var/lib/postgesql/data
  # # ports:
  # #   - 5432: 5432
  # # volumes:
  # #   - ./postges:/var/lib/postgesql/data
